FROM okteto/node:16 as builder

WORKDIR /app/builder

ENV NODE_ENV=development
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

COPY . /app/builder/

RUN npm install

ARG AM_URL=$AM_URL
ENV AM_URL=$AM_URL
ARG API_URL=$API_URL
ENV API_URL=$API_URL
ARG DEBUGGER_OFF=$DEBUGGER_OFF
ENV DEBUGGER_OFF=$DEBUGGER_OFF
ARG REALM_PATH=$REALM_PATH
ENV REALM_PATH=$REALM_PATH
ARG JOURNEY_LOGIN=$JOURNEY_LOGIN
ENV JOURNEY_LOGIN=$JOURNEY_LOGIN
ARG JOURNEY_REGISTER=$JOURNEY_REGISTER
ENV JOURNEY_REGISTER=$JOURNEY_REGISTER
ARG WEB_OAUTH_CLIENT=$WEB_OAUTH_CLIENT
ENV WEB_OAUTH_CLIENT=$WEB_OAUTH_CLIENT
ARG REST_OAUTH_CLIENT=$REST_OAUTH_CLIENT
ENV REST_OAUTH_CLIENT=$REST_OAUTH_CLIENT
ARG REST_OAUTH_SECRET=$REST_OAUTH_SECRET
ENV REST_OAUTH_SECRET=$REST_OAUTH_SECRET
ARG SCOPE=$SCOPE
ENV SCOPE=$SCOPE
ARG TIMEOUT=$TIMEOUT
ENV TIMEOUT=$TIMEOUT
ARG TREE=$TREE
ENV TREE=$TREE