services:
  todo-api:
    container_name: todo-api
    build:
      context: ./
      dockerfile: ./samples/todo-api/Dockerfile
    command: node /app/builder/dist/samples/todo-api/main.js
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      AM_URL: $AM_URL
      DEBUGGER_OFF: $DEBUGGER-OFF
      REALM_PATH: $REALM_PATH
      JOURNEY_LOGIN: $JOURNEY_LOGIN
      JOURNEY_REGISTER: $JOURNEY_REGISTER
      WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
      REST_OAUTH_CLIENT: $REST_OAUTH_CLIENT
      REST_OAUTH_SECRET: $REST_OAUTH_SECRET
    restart: on-failure
  angular-todo:
    container_name: angular-todo
    build:
      context: ./
      dockerfile: ./samples/angular-todo/Dockerfile
      args:
        AM_URL: $AM_URL
        API_URL: $API_URL
        DEBUGGER_OFF: $DEBUGGER-OFF
        REALM_PATH: $REALM_PATH
        JOURNEY_LOGIN: $JOURNEY_LOGIN
        JOURNEY_REGISTER: $JOURNEY_REGISTER
        WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
    ports:
      - '8000:80'
  central-login:
    container_name: central-login
    build:
      context: ./
      dockerfile: ./samples/central-login/Dockerfile
      args:
        AM_URL: $AM_URL
        DEBUGGER_OFF: $DEBUGGER-OFF
        REALM_PATH: $REALM_PATH
        JOURNEY_LOGIN: $JOURNEY_LOGIN
        API_URL: $API_URL
        JOURNEY_REGISTER: $JOURNEY_REGISTER
        WEB_OAUTH_CLIENT: $CENTRAL_LOGIN_CLIENT
    ports:
      - '8002:80'
    restart: on-failure
  embedded-login:
    container_name: embedded-login
    build:
      context: ./
      dockerfile: ./samples/embedded-login/Dockerfile
      args:
        PORT: 8081
        AM_URL: $AM_URL
        DEBUGGER_OFF: $DEBUGGER-OFF
        REALM_PATH: $REALM_PATH
        JOURNEY_LOGIN: $JOURNEY_LOGIN
        JOURNEY_REGISTER: $JOURNEY_REGISTER
        WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
        TREE: $TREE
        SCOPE: $SCOPE
    ports:
      - '8001:80'
    restart: on-failure
  reactjs-todo:
    container_name: reactjs-todo
    build:
      context: ./
      dockerfile: ./samples/reactjs-todo/Dockerfile
      args:
        AM_URL: $AM_URL
        DEBUGGER_OFF: $DEBUGGER-OFF
        REALM_PATH: $REALM_PATH
        API_URL: $API_URL
        JOURNEY_LOGIN: $JOURNEY_LOGIN
        JOURNEY_REGISTER: $JOURNEY_REGISTER
        WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
    ports:
      - '8443:80'
    restart: on-failure
