packages:
  - packages/*
  - e2e/*

catalog:
  '@types/node': 18.19.26
  vite-plugin-dts: ^3.8.3
  vitest-canvas-mock: ^0.3.3
  uuid: ^9.0.1

catalogs:
  express:
    express: ^4.18.3
    '@types/express': 4.17.17
    cookie-parser: ^1.4.6
    cors: '^2.8.5'
    superagent: ^8.1.2

  effect:
    '@effect/language-service': ^0.1.0
    '@effect/platform': ^0.58.27
    '@effect/platform-node': ^0.53.26
    '@effect/schema': ^0.68.23
    '@effect/vitest': ^0.6.7
    effect: ^3.5.3
    effect-http: ^0.73.0
    effect-http-node: ^0.16.1
    fast-check: ^3.19.0

  playwright:
    '@playwright/test': ^1.43.0
    playwright: ^1.43.0
