name: Setup publish
description: Setup steps for publishing packages

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false # don't install any packages yet

    - name: Install Node.js
      uses: actions/setup-node@v4
      id: cache
      with:
        node-version: '.node-version'
        cache: 'pnpm' # package manager for caching
        registry-url: 'https://registry.npmjs.org'

    # Update npm to latest for provenance
    - name: Update npm
      run: npm install -g npm@latest

    - name: Install dependencies from lockfile
      run: pnpm install --frozen-lockfile

    # Allocate nx tasks across multiple machines/agents in the cloud
    # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
    # https://nx.dev/docs/features/ci-features/distribute-task-execution
    - name: Enable distribution of nx tasks to cloud agents
      run: pnpm dlx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci" --with-env-vars="CODECOV_TOKEN"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # https://github.com/microsoft/playwright/issues/7249#issuecomment-1256878540
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      run: pnpm exec playwright install

    - name: Derive SHAs for `nx affected`
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: master

    - name: Run build, lint, test, and e2e for projects changed
      run: pnpm exec nx affected -t build lint test e2e-ci --agents

    - name: Save Playwright test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: |
          ./dist/.playwright/**
          ./dist/**
        retention-days: 30

    - name: Ensure builds for all packages before publishing
      run: pnpm exec nx run-many -t build --no-agents # --no-agents to run in CI without distributing to agents
