export const frWellKnown = {
  request_parameter_supported: true,
  pushed_authorization_request_endpoint:
    'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/par',
  introspection_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'RSA-OAEP',
    'ECDH-ES+A128KW',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  claims_parameter_supported: false,
  introspection_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/introspect',
  issuer: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha',
  id_token_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  userinfo_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  authorization_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/authorize',
  authorization_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'RSA-OAEP',
    'ECDH-ES+A128KW',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  introspection_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  claims_supported: [],
  rcs_request_signing_alg_values_supported: [
    'PS384',
    'ES384',
    'RS384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  token_endpoint_auth_methods_supported: [
    'client_secret_post',
    'private_key_jwt',
    'self_signed_tls_client_auth',
    'tls_client_auth',
    'none',
    'client_secret_basic',
  ],
  tls_client_certificate_bound_access_tokens: true,
  response_modes_supported: [
    'fragment.jwt',
    'form_post',
    'form_post.jwt',
    'jwt',
    'fragment',
    'query.jwt',
    'query',
  ],
  backchannel_logout_session_supported: true,
  token_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/access_token',
  response_types_supported: [
    'code token id_token',
    'code',
    'code id_token',
    'device_code',
    'id_token',
    'code token',
    'token',
    'token id_token',
  ],
  authorization_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  revocation_endpoint_auth_methods_supported: [
    'client_secret_post',
    'private_key_jwt',
    'self_signed_tls_client_auth',
    'tls_client_auth',
    'none',
    'client_secret_basic',
  ],
  request_uri_parameter_supported: true,
  grant_types_supported: [
    'implicit',
    'urn:ietf:params:oauth:grant-type:saml2-bearer',
    'refresh_token',
    'password',
    'client_credentials',
    'urn:ietf:params:oauth:grant-type:device_code',
    'authorization_code',
    'urn:openid:params:grant-type:ciba',
    'urn:ietf:params:oauth:grant-type:uma-ticket',
    'urn:ietf:params:oauth:grant-type:jwt-bearer',
  ],
  version: '3.0',
  prompt_values_supported: ['none', 'login', 'consent'],
  userinfo_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/userinfo',
  require_request_uri_registration: true,
  code_challenge_methods_supported: ['plain', 'S256'],
  id_token_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'RSA-OAEP',
    'ECDH-ES+A128KW',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  authorization_signing_alg_values_supported: [
    'PS384',
    'RS384',
    'EdDSA',
    'ES384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  request_object_signing_alg_values_supported: [
    'PS384',
    'ES384',
    'RS384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  request_object_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'ECDH-ES+A128KW',
    'RSA-OAEP',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  rcs_response_signing_alg_values_supported: [
    'PS384',
    'ES384',
    'RS384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  introspection_signing_alg_values_supported: [
    'PS384',
    'RS384',
    'EdDSA',
    'ES384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  check_session_iframe:
    'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/connect/checkSession',
  scopes_supported: [
    'address',
    'phone',
    'openid',
    'profile',
    'fr:idm:*',
    'am-introspect-all-tokens',
    'email',
  ],
  backchannel_logout_supported: true,
  acr_values_supported: [],
  request_object_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  rcs_request_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'RSA-OAEP',
    'ECDH-ES+A128KW',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  userinfo_signing_alg_values_supported: [
    'ES384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
  ],
  require_pushed_authorization_requests: false,
  rcs_response_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  userinfo_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'RSA-OAEP',
    'ECDH-ES+A128KW',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  end_session_endpoint:
    'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/connect/endSession',
  rcs_request_encryption_enc_values_supported: [
    'A256GCM',
    'A192GCM',
    'A128GCM',
    'A128CBC-HS256',
    'A192CBC-HS384',
    'A256CBC-HS512',
  ],
  revocation_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/token/revoke',
  rcs_response_encryption_alg_values_supported: [
    'ECDH-ES+A256KW',
    'ECDH-ES+A192KW',
    'ECDH-ES+A128KW',
    'RSA-OAEP',
    'RSA-OAEP-256',
    'A128KW',
    'A256KW',
    'ECDH-ES',
    'dir',
    'A192KW',
  ],
  token_endpoint_auth_signing_alg_values_supported: [
    'PS384',
    'ES384',
    'RS384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  jwks_uri: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/connect/jwk_uri',
  subject_types_supported: ['public', 'pairwise'],
  id_token_signing_alg_values_supported: [
    'PS384',
    'ES384',
    'RS384',
    'HS256',
    'HS512',
    'ES256',
    'RS256',
    'HS384',
    'ES512',
    'PS256',
    'PS512',
    'RS512',
  ],
  registration_endpoint: 'https://openam-spetrov.forgeblocks.com:443/am/oauth2/alpha/register',
};

export const piWellKnown = {
  issuer: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as',
  authorization_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/authorize',
  pushed_authorization_request_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/par',
  token_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/token',
  userinfo_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/userinfo',
  jwks_uri: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/jwks',
  end_session_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/signoff',
  introspection_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/introspect',
  revocation_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/revoke',
  device_authorization_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/device_authorization',
  claims_parameter_supported: false,
  request_parameter_supported: true,
  request_uri_parameter_supported: false,
  require_pushed_authorization_requests: false,
  scopes_supported: ['openid', 'profile', 'email', 'address', 'phone'],
  response_types_supported: [
    'code',
    'id_token',
    'token id_token',
    'code id_token',
    'code token',
    'code token id_token',
  ],
  response_modes_supported: ['pi.flow', 'query', 'fragment', 'form_post'],
  grant_types_supported: [
    'authorization_code',
    'implicit',
    'client_credentials',
    'refresh_token',
    'urn:ietf:params:oauth:grant-type:device_code',
  ],
  subject_types_supported: ['public'],
  id_token_signing_alg_values_supported: ['RS256'],
  userinfo_signing_alg_values_supported: ['none'],
  request_object_signing_alg_values_supported: [
    'none',
    'HS256',
    'HS384',
    'HS512',
    'RS256',
    'RS384',
    'RS512',
  ],
  token_endpoint_auth_methods_supported: [
    'client_secret_basic',
    'client_secret_post',
    'client_secret_jwt',
    'private_key_jwt',
  ],
  token_endpoint_auth_signing_alg_values_supported: [
    'HS256',
    'HS384',
    'HS512',
    'RS256',
    'RS384',
    'RS512',
  ],
  claim_types_supported: ['normal'],
  claims_supported: [
    'sub',
    'iss',
    'auth_time',
    'acr',
    'name',
    'given_name',
    'family_name',
    'middle_name',
    'preferred_username',
    'profile',
    'picture',
    'zoneinfo',
    'phone_number',
    'updated_at',
    'address',
    'email',
    'locale',
  ],
  code_challenge_methods_supported: ['plain', 'S256'],
};

export const newPiWellKnown = {
  issuer: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as',
  authorization_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/authorize',
  pushed_authorization_request_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/par',
  token_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/token',
  userinfo_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/userinfo',
  jwks_uri: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/jwks',
  end_session_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/signoff',
  ping_end_idp_session_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/idpSignoff',
  introspection_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/introspect',
  revocation_endpoint: 'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/revoke',
  device_authorization_endpoint:
    'https://auth.pingone.ca/02fb4743-189a-4bc7-9d6c-a919edfe6447/as/device_authorization',
  claims_parameter_supported: false,
  request_parameter_supported: true,
  request_uri_parameter_supported: false,
  require_pushed_authorization_requests: false,
  scopes_supported: ['openid', 'profile', 'email', 'address', 'phone', 'offline_access'],
  response_types_supported: [
    'code',
    'id_token',
    'token id_token',
    'code id_token',
    'code token',
    'code token id_token',
  ],
  response_modes_supported: ['pi.flow', 'query', 'fragment', 'form_post'],
  grant_types_supported: [
    'authorization_code',
    'implicit',
    'client_credentials',
    'refresh_token',
    'urn:ietf:params:oauth:grant-type:device_code',
  ],
  subject_types_supported: ['public'],
  id_token_signing_alg_values_supported: ['RS256'],
  userinfo_signing_alg_values_supported: ['none'],
  request_object_signing_alg_values_supported: [
    'none',
    'HS256',
    'HS384',
    'HS512',
    'RS256',
    'RS384',
    'RS512',
  ],
  token_endpoint_auth_methods_supported: [
    'client_secret_basic',
    'client_secret_post',
    'client_secret_jwt',
    'private_key_jwt',
  ],
  token_endpoint_auth_signing_alg_values_supported: [
    'HS256',
    'HS384',
    'HS512',
    'RS256',
    'RS384',
    'RS512',
  ],
  claim_types_supported: ['normal'],
  claims_supported: [
    'sub',
    'iss',
    'auth_time',
    'acr',
    'name',
    'given_name',
    'family_name',
    'middle_name',
    'preferred_username',
    'profile',
    'picture',
    'zoneinfo',
    'phone_number',
    'updated_at',
    'address',
    'email',
    'locale',
  ],
  code_challenge_methods_supported: ['plain', 'S256'],
};
