name: ForgeRock Pull Request CI
on:
  pull_request:
env:
  NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

# Needed for nx-set-shas when run on the master branch
permissions:
  actions: read
  contents: read

jobs:
  pr:
    strategy:
      matrix:
        node: [20.x]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e" # this line enables distribution
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm
      - name: Install dependencies if cache invalid
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            **/node_modules
          key: npm-dependencies-${{ hashFiles('**/package-lock.json') }}

      - run: sudo echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" | sudo tee -a /etc/hosts

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref }}
      - run: echo ${{  github.base_ref }}
      - if: ${{ github.base_ref }} == 'develop'
        run: git branch --track develop origin/develop

      - if: ${{  github.base_ref }} == 'master'
        run: git branch --track master origin/master

      - run: npx nx affected -t lint test build --parallel=3
      - run: npx nx affected --t e2e --parallel 1 --exclude token-vault-suites

      - name: Slack Notify
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "title": "${{ github.event.pull_request.title }}",
              "author": "${{ github.event.pull_request.user.login }}",
              "pr_number": "${{ github.event.pull_request.number}}",
              "url": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
