name: ForgeRock Windows CI
on: [push, pull_request]

jobs:
  install-deps-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_BROWSERS_PATH: 0

  distributed-task-windows:
    runs-on: windows-latest
    needs: install-deps-windows
    strategy:
      matrix:
        target:
          ['"test --configuration=unit"', 'build', '"test --configuration=integration"', 'e2e']
        jobIndex: [1, 2, 3, 4]
    env:
      jobCount: 4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup custom host for sdkapp.example.com
        if: ${{ matrix.target == 'e2e' }}
        run: echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" >> C:\Windows\System32\drivers\etc\hosts #add to new line

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Nx
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('package-lock.json') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('package-lock.json') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-
            cache-nx-${{ hashFiles('package-lock.json') }}-

      - run: git fetch --no-tags --prune --depth=5 origin develop
        if: ${{ !env.ACT }}

      - name: nx run-many:${{ matrix.target }}
        run: node ./tools/scripts/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() || success() }}
        with:
          name: 'E2E Artifacts'
          path: test-results/
          retention-days: 5
